import '@styles/globals.css'

export const metadata = {
  title: 'Admin Template',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}

export default RootLayout;
