import '@styles/globals.css'
import Aside from "@components/Aside";

export const metadata = {
  title: 'Admin Template',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className='flex bg-blue-50'>
        {/* Main aside navigation */}
        <Aside />

        <main>
          {children}
        </main>
      </body>
    </html>
  )
}

export default RootLayout;
